=begin comment

DaDaPush Public API

DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.

The version of the OpenAPI document: v1
Contact: contacts@dadapush.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('DaDaPushClient::DaDaPushMessageApi');

my $api = DaDaPushClient::DaDaPushMessageApi->new();
isa_ok($api, 'DaDaPushClient::DaDaPushMessageApi');

#
# create_message test
#
{
    my $body = undef; # replace NULL with a proper value
    my $x_channel_token = undef; # replace NULL with a proper value
    my $result = $api->create_message(body => $body, x_channel_token => $x_channel_token);
}

#
# delete_message test
#
{
    my $message_id = undef; # replace NULL with a proper value
    my $x_channel_token = undef; # replace NULL with a proper value
    my $result = $api->delete_message(message_id => $message_id, x_channel_token => $x_channel_token);
}

#
# get_message test
#
{
    my $message_id = undef; # replace NULL with a proper value
    my $x_channel_token = undef; # replace NULL with a proper value
    my $result = $api->get_message(message_id => $message_id, x_channel_token => $x_channel_token);
}

#
# get_messages test
#
{
    my $page = undef; # replace NULL with a proper value
    my $page_size = undef; # replace NULL with a proper value
    my $x_channel_token = undef; # replace NULL with a proper value
    my $result = $api->get_messages(page => $page, page_size => $page_size, x_channel_token => $x_channel_token);
}


1;
