=begin comment

DaDaPush Public API

DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.

The version of the OpenAPI document: v1
Contact: contacts@dadapush.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by the OpenAPI Generator
# Please update the test cases below to test the model.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 2;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;


use_ok('DaDaPushClient::Object::MessagePushResponse');

my $instance = DaDaPushClient::Object::MessagePushResponse->new();

isa_ok($instance, 'DaDaPushClient::Object::MessagePushResponse');

